import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

const glyphBytes = 32;
const fontPath = resolve(import.meta.dir, '../../source/Doraemon/chifont.dat');
const destination = resolve(import.meta.dir, '../src/lib/generated/chifont.ts');
const font = await readFile(fontPath);

if (font.length % glyphBytes !== 0) {
  throw new Error(`${fontPath} is not a 16×16 monochrome glyph file`);
}

const encoded = font.toString('base64');
const source = `// Generated by scripts/generate-font.ts. Do not edit.\n\n` +
  `const encoded = '${encoded}';\n\n` +
  `export const glyphCount = ${font.length / glyphBytes};\n` +
  `export const glyphBytes = Uint8Array.from(atob(encoded), (character) => character.charCodeAt(0));\n`;

await mkdir(dirname(destination), { recursive: true });
await writeFile(destination, source);
console.log(`Generated ${font.length / glyphBytes} glyphs from ${fontPath}`);
