import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

const fontPath = resolve(import.meta.dir, '../../source/Doraemon/sysfont.dat');
const destination = resolve(import.meta.dir, '../src/lib/generated/sysfont-metrics.ts');
const font = new Uint8Array(await readFile(fontPath));

const u16 = (offset: number) => font[offset] | (font[offset + 1] << 8);
const u32 = (offset: number) => (font[offset] | (font[offset + 1] << 8) | (font[offset + 2] << 16) | (font[offset + 3] << 24)) >>> 0;
const count = u16(0);
if (!count || count % 128 || 2 + count * 4 > font.length) throw new Error('Invalid sysfont.dat.');

const variants = Array.from({ length: count / 128 }, (_, variant) =>
  Array.from({ length: 128 }, (_, code) => font[u32(2 + (variant * 128 + code) * 4)])
);

const source = `// Generated by scripts/generate-sysfont-metrics.ts. Do not edit.\n\n` +
  `export const SYSFONT_WIDTHS = ${JSON.stringify(variants)} as const;\n`;

await mkdir(dirname(destination), { recursive: true });
await writeFile(destination, source);
console.log(`Generated ${variants.length} sysfont width tables from ${fontPath}`);
