[package]
name = "doraemon-patcher"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
build = "build.rs"

[dependencies]
doraemon-game-patch = { path = "../game-patch" }

[build-dependencies]
slint-build = "=1.9.2"

[target.'cfg(windows)'.dependencies]
slint = { version = "=1.9.2", default-features = false, features = ["std", "backend-winit", "renderer-software", "compat-1-2"] }
winapi = { version = "0.3", features = ["winuser", "winerror"] }
